// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateHouse(ctx context.Context, arg CreateHouseParams) (House, error)
	CreateRentalAgreement(ctx context.Context, arg CreateRentalAgreementParams) (RentalAgreement, error)
	CreateRentalUnit(ctx context.Context, arg CreateRentalUnitParams) (RentalUnit, error)
	CreateRenter(ctx context.Context, fullName string) (Renter, error)
	DeleteHouse(ctx context.Context, id int32) (House, error)
	DeleteRentalAgreement(ctx context.Context, id int32) (RentalAgreement, error)
	DeleteRentalUnit(ctx context.Context, id int32) (RentalUnit, error)
	DeleteRentalUnitsByHouse(ctx context.Context, houseID int32) ([]int32, error)
	DeleteRenter(ctx context.Context, id int32) (Renter, error)
	ExtendRentalAgreement(ctx context.Context, arg ExtendRentalAgreementParams) (RentalAgreement, error)
	GetHouse(ctx context.Context, id int32) (House, error)
	GetHouses(ctx context.Context, arg GetHousesParams) ([]House, error)
	GetRentalAgreement(ctx context.Context, id int32) (RentalAgreement, error)
	GetRentalAgreementsByRenter(ctx context.Context, arg GetRentalAgreementsByRenterParams) ([]RentalAgreement, error)
	GetRentalUnit(ctx context.Context, id int32) (RentalUnit, error)
	GetRentalUnitsByHouse(ctx context.Context, arg GetRentalUnitsByHouseParams) ([]RentalUnit, error)
	GetRenter(ctx context.Context, id int32) (Renter, error)
	GetRenters(ctx context.Context, arg GetRentersParams) ([]Renter, error)
	UpdateHouseInfo(ctx context.Context, arg UpdateHouseInfoParams) (House, error)
	UpdateRentalUnit(ctx context.Context, arg UpdateRentalUnitParams) (RentalUnit, error)
}

var _ Querier = (*Queries)(nil)
